import { Color4 } from '@dcl/sdk/math'

export const EasingFunctionObject = {
  /** EF_LINEAR - default */
  EF_LINEAR: 0,
  EF_EASEINQUAD: 1,
  EF_EASEOUTQUAD: 2,
  EF_EASEQUAD: 3,
  EF_EASEINSINE: 4,
  EF_EASEOUTSINE: 5,
  EF_EASESINE: 6,
  EF_EASEINEXPO: 7,
  EF_EASEOUTEXPO: 8,
  EF_EASEEXPO: 9,
  EF_EASEINELASTIC: 10,
  EF_EASEOUTELASTIC: 11,
  EF_EASEELASTIC: 12,
  EF_EASEINBOUNCE: 13,
  EF_EASEOUTBOUNCE: 14,
  EF_EASEBOUNCE: 15,
  EF_EASEINCUBIC: 16,
  EF_EASEOUTCUBIC: 17,
  EF_EASECUBIC: 18,
  EF_EASEINQUART: 19,
  EF_EASEOUTQUART: 20,
  EF_EASEQUART: 21,
  EF_EASEINQUINT: 22,
  EF_EASEOUTQUINT: 23,
  EF_EASEQUINT: 24,
  EF_EASEINCIRC: 25,
  EF_EASEOUTCIRC: 26,
  EF_EASECIRC: 27,
  EF_EASEINBACK: 28,
  EF_EASEOUTBACK: 29,
  EF_EASEBACK: 30
}

export const EasingFunctionKeys = Object.keys(EasingFunctionObject)

export const WhiteAlphaBackgroundColor = Color4.create(1, 1, 1, 0.2)
